routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\MainPageController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\RestController;
use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('mainpage');
});

Route::get('/', [MainPageController::class, 'category']);
Route::get('/{category_name}', [MainPageController::class, 'sortToCategory']);

// Route::get('/cabinet', function () {
//     return view('cabinet');
// })->middleware(['auth', 'verified'])->name('cabinet');

Route::get('/cabinet')->middleware(['checkAuth']);

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::post('/articles/delete', [ArticleController::class, 'delete'])->name('articles.delete');
Route::resource('articles', ArticleController::class);
Route::post('/authors/delete', [AuthorController::class, 'delete'])->name('authors.delete');
Route::resource('authors', AuthorController::class);
Route::post('/category/delete', [CategoryController::class, 'delete'])->name('category.delete');
Route::resource('category', CategoryController::class);

Route::get('crud/category', function () {
    return view('crud/category');
});
Route::get('crud/category', [CategoryController::class, 'index']);
Route::get('profile/edit', [ProfileController::class, 'edit'])->name('profile.edit');

Route::get('crud/author', function () {
    return view('crud/author');
});
Route::get('crud/author', [AuthorController::class, 'index']);

Route::get('crud/article', function () {
    return view('crud/article');
});
Route::get('crud/article', [ArticleController::class, 'index']);

Route::get('data/rest', function () {
    return view('data/rest');
});
Route::get('data/rest', [RestController::class, 'index']);

require __DIR__.'/auth.php';

resources/views/crud/article.blade.php
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Philosophy</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{{ mix('/css/base.css') }} ">
    <link rel="stylesheet" href="../css/vendor.css"> 
    <link rel="stylesheet" href="../css/main.css">

   

    <!-- script
    ================================================== -->
    <script src="../js/modernizr.js"></script>
    <script src="../js/pace.min.js"></script>

    <!-- favicons
    ================================================== -->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="icon" href="favicon.ico" type="image/x-icon">


</head>

<body id="top">

    <div class="header-logo-auth">
    <div class="header__logo">
        <a class="logo" href="{{ url('/') }}">
            <img src="../images/logo.svg" alt="Homepage">
        </a>
    </div> 

    <div class="hidden sm:flex sm:items-center sm:ml-6">
        <x-dropdown align="right" width="48">
            <x-slot name="trigger">
                <button style="width: 250px;" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 dark:text-gray-400 bg-white dark:bg-gray-800 hover:text-gray-700 dark:hover:text-gray-300 focus:outline-none transition ease-in-out duration-150">
                    <div>{{ Auth::user()->name }}</div>
                </button>
            </x-slot>

            <x-slot name="content">
                <x-dropdown-link :href="route('profile.edit')">
                    {{ __('Profile') }}
                </x-dropdown-link>

                <br><a href="{{ URL::previous() }}">Back</a>
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-dropdown-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-dropdown-link>
                </form>
            </x-slot>
        </x-dropdown>
    </div>
</div>



<div >
    <div class="" style="display: flex; justify-content: center;">
               
        <form class="form-ar-store" action="{{ route('articles.store') }}" method="POST" enctype="multipart/form-data">
          @csrf
              <div class="field">
                <input type="text" name="name" placeholder="Название" class="text-aliceblue">
              </div>
              <div class="field">
                <textarea type="text" name="text" placeholder="Текст статьи" class="text-aliceblue"></textarea>
              </div>
              <div class="field">
                <input type="file" name="image" placeholder="Название" class="text-aliceblue">
              </div>
              <div class="field">
                <select name="category" id="category" style="color: #6d6d6d;">
                    <option value="">Выберите категорию</option>
                    @foreach ($category as $categoryItem)
                    <option value="{{$categoryItem->id}}">{{$categoryItem->name}}</option>
                    @endforeach
                </select>
              </div>
              <div class="field">
                    <select name="author" id="author" style="color: #6d6d6d;">
                    <option value="">Выберите автора</option>
                    @foreach ($authors as $authorsItem)
                    <option value="{{$authorsItem->id}}">{{$authorsItem->first_name}} {{$authorsItem->last_name}}</option>
                    @endforeach
                </select>
              </div>
         
              <div>
                <button type="submit">Добавить</button>
              </div>
          </form>
          
    </div> 


    <div class="row" style="margin-left: 10%;">
        <div class="col-full">
            <nav class="pgn">
                <ul>
                   
                    <div class="divTable" style="border: 2px solid #000;" >
                        <div class="divTableBody">
                        <div class="divTableRow">
                        <div class="divTableCell">Информация о статье</div>
                        </div>
                    @foreach ($articles as $articlesItem)
                    <form class="" action="{{ route('articles.update', $articlesItem->id)}}" method="POST" >
                      @csrf
                      @method('patch')
                        <div class="divTableRow">
                        <div class="divTableCell">{{$articlesItem->id}}</div>
                        <div class="divTableCell">
                         <input type="text" name="name" value="{{$articlesItem->name}}" class="text-aliceblue">
                        </div>
                        <div class="divTableCell">
                          <textarea type="text" name="text" class="text-aliceblue">{{$articlesItem->text}}</textarea>
                        </div>
                        <div class="divTableCell">
                          <select name="author" id="author" style="color: #6d6d6d;">
                            @foreach ($authors as $authorsItem)
                            <option value="{{$authorsItem->id}}"  {{ $authorsItem->id == $articlesItem->author_id ? 'selected="selected"' : '' }}>{{$authorsItem->first_name}} {{$authorsItem->last_name}}</option>
                            
                            @endforeach
                        </select>
                        </div>
                        <div class="divTableCell">
                          <select name="category" id="category" style="color: #6d6d6d;">
                            <option value="">Выберите категорию</option>
                            @foreach ($category as $categoryItem)
                            <option value="{{$categoryItem->id}}" {{ $categoryItem->id == $articlesItem->category_id ? 'selected="selected"' : '' }}>{{$categoryItem->name}}</option>
                            @endforeach
                        </select>
                        </div>
                        <div class="divTableCell">{{Carbon\Carbon::parse($articlesItem->created_at)->format('d-m-y h:i')}}</div>
                        <div class="divTableCell">{{Carbon\Carbon::parse($articlesItem->updated_at)->format('d-m-y h:i')}}</div>
                        <div class="divTableCell">
                            @if (!empty($articlesItem->image))
                                <img src="{{ asset("../images/{$articlesItem->image}")}}" alt=""> 
                            @else
                            <img src="../images/thumbs/masonry/wheel-400.jpg" 
                            srcset="../images/thumbs/masonry/wheel-400.jpg 1x, ../images/thumbs/masonry/wheel-800.jpg 2x" alt="" style="width: 225px;height: 225px;">
                            @endif
                          {{-- <input type="file" name="image" placeholder="Название" class="text-aliceblue" value="значение"> --}}
                        </div>

                        <div class="divTableCell">
                        
                          <button>Редактировать</button></form>
                          <form class="" action="{{ route('articles.delete') }}" method="POST" >
                            @csrf
                              <div class="field">
                                  <input type="text" name="id" value="{{$articlesItem->id}}" class="text-aliceblue" style="visibility: collapse;display: none;">
                                </div>
                           
                                <div>
                                  <button type="submit">Удалить</button>
                                </div>
                            </form>
                        
                        </div>

                        </div>
                    @endforeach
                        </div>
                        </div>
                        {{ $articles->links() }}
                </ul>
            </nav>
        </div>
    </div> 



    <footer class="s-footer">

        <div class="s-footer__main">
            <div class="row">

          
                
              


            </div>
        </div> 

      

    </footer> 

    <!-- Java Script
    ================================================== -->
    <script src="js/jquery-3.2.1.min.js"></script>
    <script src="js/plugins.js"></script>
    <script src="js/main.js"></script>

</body>

</html>

resources/views/crud/author.blade.php
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Philosophy</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{{ mix('/css/base.css') }} ">
    <link rel="stylesheet" href="../css/vendor.css"> 
    <link rel="stylesheet" href="../css/main.css">

   

    <!-- script
    ================================================== -->
    <script src="../js/modernizr.js"></script>
    <script src="../js/pace.min.js"></script>

    <!-- favicons
    ================================================== -->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="icon" href="favicon.ico" type="image/x-icon">


</head>

<body id="top">

    <div class="header-logo-auth">
    <div class="header__logo">
        <a class="logo" href="{{ url('/') }}">
            <img src="../images/logo.svg" alt="Homepage">
        </a>
    </div> 

    <div class="hidden sm:flex sm:items-center sm:ml-6">
        <x-dropdown align="right" width="48">
            <x-slot name="trigger">
                <button style="width: 250px;" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 dark:text-gray-400 bg-white dark:bg-gray-800 hover:text-gray-700 dark:hover:text-gray-300 focus:outline-none transition ease-in-out duration-150">
                    <div>{{ Auth::user()->name }}</div>
                </button>
            </x-slot>

            <x-slot name="content">
                <x-dropdown-link :href="route('profile.edit')">
                    {{ __('Profile') }}
                </x-dropdown-link>

                <br><a href="{{ URL::previous() }}">Back</a>
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-dropdown-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-dropdown-link>
                </form>
            </x-slot>
        </x-dropdown>
    </div>
</div>

<div style="display: flex;justify-content: space-around;">
    <div class="">
               
        <form class="" action="{{ route('authors.store') }}" method="POST" >
          @csrf
              <div class="field">
                <input type="text" name="first_name" placeholder="Имя" class="text-aliceblue">
              </div>
              <div class="field">
                <input type="text" name="last_name" placeholder="Фамилия" class="text-aliceblue">
              </div>
         
              <div>
                <button type="submit">Добавить</button>
              </div>
          </form>
          
    </div> 

    <div class="">
           
        <form class="" action="{{ route('authors.update', 'update')}}" method="POST" >
            @method('patch')
          @csrf
              <div class="field">
                <input type="text" name="id" placeholder="Id автора" class="text-aliceblue">
              </div>

              <div class="field">
                <input type="text" name="first_name" placeholder="Имя" class="text-aliceblue">
              </div>
              <div class="field">
                <input type="text" name="last_name" placeholder="Фамилия" class="text-aliceblue">
              </div>
         
              <div>
                <button type="submit">Редактировать</button>
              </div>
          </form>
        </div> 

    <div class="">
       
        <form class="" action="{{ route('authors.delete') }}" method="POST" >
          @csrf
            <div class="field">
                <input type="text" name="id" placeholder="Id автора" class="text-aliceblue">
              </div>
         
              <div>
                <button type="submit">Удалить</button>
              </div>
          </form>
          
    </div> 


    
</div>

        
   

        <div class="row">
            <div class="col-full">
                <nav class="pgn">
                    <ul>
                       
                        <div class="divTable" style="border: 2px solid #000;" >
                            <div class="divTableBody">
                            <div class="divTableRow">
                            <div class="divTableCell">ID</div>
                            <div class="divTableCell">ИМЯ</div>
                            <div class="divTableCell">ФАМИЛИЯ</div>
                            <div class="divTableCell">СОЗДАНО</div>
                            <div class="divTableCell">ОБНОВЛЕНО</div>
                            <div class="divTableCell">КОЛИЧЕСТВО СТАТЕЙ</div>
                            </div>
                        @foreach ($authors as $authorItem)
                       
                            <div class="divTableRow">
                            <div class="divTableCell">{{$authorItem['id']}}</div>
                            <div class="divTableCell">{{$authorItem['first_name']}}</div>
                            <div class="divTableCell">{{$authorItem['last_name']}}</div>
                            <div class="divTableCell">{{Carbon\Carbon::parse($authorItem['created_at'])->format('d-m-y h:i')}}</div>
                            <div class="divTableCell">{{Carbon\Carbon::parse($authorItem['updated_at'])->format('d-m-y h:i')}}</div>
                            <div class="divTableCell">{{$authorItem['count']}}</div>
                            </div>
                        @endforeach
                            </div>
                            </div>
                    </ul>
                </nav>
            </div>
        </div> 



    <footer class="s-footer">

        <div class="s-footer__main">
            <div class="row">

          
                
              


            </div>
        </div> 

      

    </footer> 

    <!-- Java Script
    ================================================== -->
    <script src="js/jquery-3.2.1.min.js"></script>
    <script src="js/plugins.js"></script>
    <script src="js/main.js"></script>

</body>

</html>

resources/views/crud/category.blade.php
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Philosophy</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{{ mix('/css/base.css') }} ">
    <link rel="stylesheet" href="../css/vendor.css"> 
    <link rel="stylesheet" href="../css/main.css">

   

    <!-- script
    ================================================== -->
    <script src="../js/modernizr.js"></script>
    <script src="../js/pace.min.js"></script>

    <!-- favicons
    ================================================== -->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="icon" href="favicon.ico" type="image/x-icon">


</head>

<body id="top">

    <div class="header-logo-auth">
    <div class="header__logo">
        <a class="logo" href="{{ url('/') }}">
            <img src="../images/logo.svg" alt="Homepage">
        </a>
    </div> 

    <div class="hidden sm:flex sm:items-center sm:ml-6">
        <x-dropdown align="right" width="48">
            <x-slot name="trigger">
                <button style="width: 250px;" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 dark:text-gray-400 bg-white dark:bg-gray-800 hover:text-gray-700 dark:hover:text-gray-300 focus:outline-none transition ease-in-out duration-150">
                    <div>{{ Auth::user()->name }}</div>
                </button>
            </x-slot>

            <x-slot name="content">
                <x-dropdown-link :href="route('profile.edit')">
                    {{ __('Profile') }}
                </x-dropdown-link>

                <br><a href="{{ URL::previous() }}">Back</a>
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-dropdown-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-dropdown-link>
                </form>
            </x-slot>
        </x-dropdown>
    </div>
</div>

<div style="display: flex;justify-content: space-around;">
        <div class="">
                   
            <form class="" action="{{ route('category.store') }}" method="POST" >
              @csrf
                <div class="field">
                    <input type="text" name="name" placeholder="Название категории" class="text-aliceblue">
                  </div>
             
                  <div>
                    <button type="submit">Добавить</button>
                  </div>
              </form>
              
        </div> 

        <div class="">
               
            <form class="" action="{{ route('category.update', 'update')}}" method="POST" >
                @method('patch')
              @csrf
                  <div class="field">
                    <input type="text" name="id" placeholder=" Id категории" class="text-aliceblue">
                  </div>
    
                  <div class="field">
                    <input type="text" name="name" placeholder="Название категории" class="text-aliceblue">
                  </div>
             
                  <div>
                    <button type="submit">Редактировать</button>
                  </div>
              </form>
            </div> 

        <div class="">
           
            <form class="" action="{{ route('category.delete') }}" method="POST" >
              @csrf
                <div class="field">
                    <input type="text" name="name" placeholder="Название категории" class="text-aliceblue">
                  </div>
             
                  <div>
                    <button type="submit">Удалить</button>
                  </div>
              </form>
              
        </div> 


        
    </div>

        <div class="row">
            <div class="col-full">
                <nav class="pgn">
                    <ul>
                       
                        <div class="divTable" style="border: 2px solid #000;" >
                            <div class="divTableBody">
                            <div class="divTableRow">
                            <div class="divTableCell">ID</div>
                            <div class="divTableCell">НАЗВАНИЕ</div>
                            <div class="divTableCell">СОЗДАНО</div>
                            <div class="divTableCell">ОБНОВЛЕНО</div>
                            </div>
                        @foreach ($category as $categoryItem)
                        {{-- dd{{$categoryItem}}  --}}
                            <div class="divTableRow">
                            <div class="divTableCell">{{$categoryItem->id}}</div>
                            <div class="divTableCell">{{$categoryItem->name}}</div>
                            <div class="divTableCell">{{Carbon\Carbon::parse($categoryItem->created_at)->format('d-m-y h:i')}}</div>
                            <div class="divTableCell">{{Carbon\Carbon::parse($categoryItem->updated_at)->format('d-m-y h:i')}}</div>
                            </div>
                        @endforeach
                            </div>
                            </div>
                    </ul>


{{ $category->links() }}
                </nav>
            </div>
        </div> 



    <footer class="s-footer">

        <div class="s-footer__main">
            <div class="row">

          
                
              


            </div>
        </div> 

      

    </footer> 

    <!-- Java Script
    ================================================== -->
    <script src="js/jquery-3.2.1.min.js"></script>
    <script src="js/plugins.js"></script>
    <script src="js/main.js"></script>

</body>

</html>